<?php

/**
 * @file
 * Demonstrates render arrays.
 */

/**
 * @defgroup render_example Example: Render
 * @ingroup examples
 * @{
 * Demonstrate how render arrays are arranged and how they can be altered.
 * This alters blocks and the page to show the actual render array
 * that is being used to create each item.
 *
 * @see drupal_render()
 */

// This allows drupal_var_export() to work.
require_once('includes/utility.inc');

/**
 * Implements hook_menu().
 */
function render_example_menu() {
  $items['examples/render_example'] = array(
    'title'           => 'Render Example',
    'page callback'   => 'render_example_info',
    'access callback' => TRUE,
  );
  $items['examples/render_example/altering'] = array(
    'title' => 'Alter pages and blocks',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('render_example_demo_form'),
    'access arguments' => array('access devel information'),
  );
  $items['examples/render_example/arrays'] = array(
    'title'           => 'Render array examples',
    'page callback'   => 'render_example_arrays',
    'access callback' => TRUE,
  );

  return $items;
}


/**
 * Simple basic information about the module; an entry point.
 */
function render_example_info() {
  return t('The render example provides a <ul><li><a href="!arrays">demonstration of of render array usage</a></li><li><a href="!alter">using hook_page_alter()</a> to make various changes on a page.</li></ul>', array('!arrays' => url('examples/render_example/arrays'), '!alter' => url('examples/render_example/altering')));
}


/*************** Altering Section **************************
 * The following section of the example builds and arranges the altering
 * example.
 */

/**
 * Builds the form that offers options of what items to show.
 */
function render_example_demo_form($form, &$form_state) {
  $form['description'] = array(
    '#type'   => 'markup',
    '#markup' => t('This example shows what render arrays look like in the building of a page. It will not work unless the user running it has the "access devel information" privilege. It shows both the actual arrays used to build a page or block and also the capabilities of altering the page late in its lifecycle.'),
  );

  $form['show_arrays'] = array(
    '#type'  => 'fieldset',
    '#title' => t('Show render arrays'),
  );

  foreach (array('block', 'page') as $type) {
    $form['show_arrays']['render_example_show_' . $type] = array(
      '#type'          => 'checkbox',
      '#title'         => t('Show @type render arrays', array('@type' => $type)),
      '#default_value' => variable_get('render_example_show_' . $type, FALSE),
    );
  }

  $form['page_fiddling'] = array(
    '#type'  => 'fieldset',
    '#title' => t('Make changes on page via hook_page_alter()'),
  );
  $form['page_fiddling']['render_example_note_about_render_arrays'] = array(
    '#title'         => t('Add a note about render arrays to top of sidebar_first (if it exists)'),
    '#description'   => t('Creates a simple render array that displays the use of #pre_render, #post_render, #theme, and #theme_wrappers.'),
    '#type'          => 'checkbox',
    '#default_value' => variable_get('render_example_note_about_render_arrays', FALSE),
  );
  $form['page_fiddling']['render_example_move_navigation_menu'] = array(
    '#title'         => t('Move the navigation menu to the top of the content area'),
    '#description'   => t('Uses hook_page_alter() to move the navigation menu into another region.'),
    '#type'          => 'checkbox',
    '#default_value' => variable_get('render_example_move_navigation_menu', FALSE),
  );
  $form['page_fiddling']['render_example_reverse_sidebar'] = array(
    '#title'         => t('Reverse ordering of sidebar_first elements (if it exists) - will affect the above'),
    '#description'   => t('Uses hook_page_alter() to reverse the ordering of items in sidebar_first'),
    '#type'          => 'checkbox',
    '#default_value' => variable_get('render_example_reverse_sidebar', FALSE),
  );
  $form['page_fiddling']['render_example_prefix'] = array(
    '#title'         => t('Use #prefix and #suffix to wrap a div around every block'),
    '#description'   => t('Uses hook_page_alter to wrap all blocks with a div using #prefix and #suffix'),
    '#type'          => 'checkbox',
    '#default_value' => variable_get('render_example_prefix'),
  );

  return system_settings_form($form);
}


